// Copyright 2010-2013, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is generated by a script at first but now maintained manually.

#ifndef MOZC_LANGUAGES_PINYIN_UNIX_IBUS_MAIN_H_
#define MOZC_LANGUAGES_PINYIN_UNIX_IBUS_MAIN_H_
namespace {
const char kComponentVersion[] = "0.0.0.0";
const char kComponentName[] = "com.google.IBus.Pinyin";
const char kComponentLicense[] = "New BSD";
const char kComponentExec[] = "/usr/libexec/ibus-engine-mozc-pinyin --ibus";
const char kComponentTextdomain[] = "ibus-mozc-pinyin";
const char kComponentAuthor[] = "Google Inc.";
const char kComponentHomepage[] = "http://code.google.com/p/mozc/";
const char kComponentDescription[] = "Mozc Pinyin Component";
const char kEngineRank[] = "0";
const char kEngineDescription[] = "Mozc Pinyin (Pinyin Input Method)";
const char kEngineLanguage[] = "zh-CN";
const char kEngineIcon[] = "/usr/share/ibus-mozc/product_icon.png";
const char *kEngineLayoutArray[] = {
  "us",
  "us(dvorak)",
};
const char *kEngineNameArray[] = {
  "mozc-pinyin",
  "mozc-pinyin-dv",
};
const char *kEngineLongnameArray[] = {
  "Mozc Pinyin",
  "Mozc Pinyin (for US Dvorak keyboard)",
};
const size_t kEngineArrayLen = 2;
}  // namespace
#endif  // MOZC_LANGUAGES_PINYIN_UNIX_IBUS_MAIN_H_
