// Copyright 2010-2021, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef MOZC_DICTIONARY_USER_POS_H_
#define MOZC_DICTIONARY_USER_POS_H_

#include <cstddef>
#include <cstdint>
#include <iterator>
#include <memory>
#include <optional>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include "absl/strings/string_view.h"
#include "base/bits.h"
#include "base/container/serialized_string_array.h"
#include "protocol/user_dictionary_storage.pb.h"

namespace mozc {
namespace dictionary {

// This implementation of UserPos uses a sorted array of tokens to
// efficiently lookup required data.  There are two required data, string array
// and token array, which are generated by ./gen_user_pos_data.py.
//
// * Prerequisite
// Little endian is assumed.
//
// * Binary format
//
// ** String array
// All the strings, such as key and value suffixes, are serialized into one
// array using SerializedStringArray in such a way that array is sorted in
// ascending order.  In the token array (see below), every string is stored as
// an index to this array.
//
// ** Token array
//
// The token array is an array of 8 byte blocks each of which has the following
// layout:
//
// Token layout (8 bytes)
// +---------------------------------------+
// | POS index  (2 bytes)                  |
// + - - - - - - - - - - - - - - - - - - - +
// | Value suffix index (2 bytes)          |
// + - - - - - - - - - - - - - - - - - - - +
// | Key suffix index  (2 bytes)           |
// + - - - - - - - - - - - - - - - - - - - +
// | Conjugation ID (2 bytes)              |
// +---------------------------------------+
//
// The array is sorted in ascending order of POS index so that we can use binary
// search to lookup necessary information efficiently.  Note that there are
// tokens having the same POS index.
class UserPos {
 public:
  struct Token {
    std::string key;
    std::string value;
    uint16_t id = 0;  // internal POS id used for lid/rid.
    uint8_t attributes = 0;
    uint8_t raw_pos_type = 0;  // POS information. UserDictionary::PosType.
    // The actual cost of user dictionary entries are populated
    // in the dictionary lookup time via PopulateTokenFromUserPosToken.
    std::string comment;  // This field comes from user dictionary.

    // Attribute is used to dynamically assign cost, and is independent from the
    // POS.
    // TODO(taku): Better to remove it as we only have one field.
    enum Attribute {
      NON_JA_LOCALE = 1  // Locale is not Japanese.
    };

    inline void add_attribute(Attribute attr) { attributes |= attr; }
    inline bool has_attribute(Attribute attr) const {
      return attributes & attr;
    }
    inline void remove_attribute(Attribute attr) { attributes &= ~attr; }
    inline user_dictionary::UserDictionary::PosType pos_type() const {
      return static_cast<::mozc::user_dictionary::UserDictionary::PosType>(
          raw_pos_type);
    }
    inline void set_pos_type(
        user_dictionary::UserDictionary::PosType pos_type) {
      raw_pos_type = static_cast<uint8_t>(pos_type);
    }
  };

  // Initializes the user pos from the given binary data.  The provided byte
  // data must outlive this instance.
  UserPos(absl::string_view token_array_data,
          absl::string_view string_array_data);
  UserPos(const UserPos&) = default;
  UserPos& operator=(const UserPos&) = default;
  virtual ~UserPos() = default;

  // Virutal for testing/mocking.
  virtual std::vector<std::string> GetPosList() const { return pos_list_; }
  virtual int GetPosListDefaultIndex() const { return pos_list_default_index_; }
  virtual std::optional<uint16_t> GetPosIds(absl::string_view pos) const;
  virtual bool IsValidPos(absl::string_view pos) const {
    return GetPosIds(pos).has_value();
  }
  virtual std::vector<UserPos::Token> GetTokens(
      absl::string_view key, absl::string_view value,
      user_dictionary::UserDictionary::PosType pos_type,
      absl::string_view locale) const;

  std::vector<UserPos::Token> GetTokens(absl::string_view key,
                                        absl::string_view value,
                                        absl::string_view pos,
                                        absl::string_view locale) const {
    return GetTokens(key, value, ToPosType(pos), locale);
  }

  std::vector<Token> GetTokens(
      absl::string_view key, absl::string_view value,
      user_dictionary::UserDictionary::PosType pos_type) const {
    return GetTokens(key, value, pos_type, "");
  }

  std::vector<UserPos::Token> GetTokens(absl::string_view key,
                                        absl::string_view value,
                                        absl::string_view pos) const {
    return GetTokens(key, value, ToPosType(pos), "");
  }

  // Returns the string representation of PosType, or empty string if the given
  // pos is invalid.
  // For historical reason, the pos was represented in Japanese characters.
  static absl::string_view GetStringPosType(
      user_dictionary::UserDictionary::PosType pos_type);

  // Returns the cost of PosType. if cost is not defined, the default cost
  // is returned.
  static uint16_t GetCostFromPosType(
      user_dictionary::UserDictionary::PosType pos_type);

  // Returns the string representation of PosType. INVALID if the given pos is
  // invalid.
  static user_dictionary::UserDictionary::PosType ToPosType(
      absl::string_view string_pos_type);

 protected:
  // For testing.
  UserPos() = default;

 private:
  struct TokenArrayData {
    uint16_t pos_index;
    uint16_t value_suffix_index;
    uint16_t key_suffix_index;
    uint16_t conjugation_id;
  };

  static_assert(sizeof(TokenArrayData) == 8);

  void InitPosList();

  inline TokenArrayData GetTokenArrayData(size_t i) const {
    const char* ptr = token_array_data_.data() + i * sizeof(TokenArrayData);
    return {LoadUnaligned<uint16_t>(ptr), LoadUnaligned<uint16_t>(ptr + 2),
            LoadUnaligned<uint16_t>(ptr + 4), LoadUnaligned<uint16_t>(ptr + 6)};
  }

  inline size_t TokenArrayDataSize() const {
    return token_array_data_.size() / sizeof(TokenArrayData);
  }

  absl::string_view token_array_data_;
  // token_array_index_[pos_type] = {index to token_array_data_};
  std::vector<std::vector<int>> token_array_index_;
  SerializedStringArray string_array_;
  std::vector<std::string> pos_list_;
  int pos_list_default_index_ = 0;
};

}  // namespace dictionary
}  // namespace mozc

#endif  // MOZC_DICTIONARY_USER_POS_H_
