# -*- coding: utf-8 -*-
# Copyright 2010-2021, Google Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#     * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

filegroup(
    name = "composition_table",
    srcs = [
        "12keys-halfwidthascii.tsv",
        "12keys-hiragana.tsv",
        "12keys-hiragana_intuitive.tsv",
        "flick-halfwidthascii.tsv",
        "flick-halfwidthascii_ios.tsv",
        "flick-hiragana.tsv",
        "flick-hiragana_intuitive.tsv",
        "flick-number.tsv",
        "godan-hiragana.tsv",
        "hiragana-romanji.tsv",
        "kana.tsv",
        "notouch-hiragana.tsv",
        "qwerty_mobile-halfwidthascii.tsv",
        "qwerty_mobile-hiragana.tsv",
        "romanji-hiragana.tsv",
        "toggle_flick-halfwidthascii.tsv",
        "toggle_flick-halfwidthascii_ios.tsv",
        "toggle_flick-hiragana.tsv",
        "toggle_flick-hiragana_intuitive.tsv",
        "toggle_flick-number.tsv",
    ],
    visibility = ["//base:__pkg__"],
)

exports_files(glob(["*.tsv"]))
