#!/bin/sh

_BUILD_TARGETS="${_BUILD_TARGETS:-server/server.gyp:mozc_server gui/gui.gyp:mozc_tool unix/fcitx5/fcitx5.gyp:fcitx5-mozc}"
_bldtype="${_bldtype:-Debug}"

python build_mozc.py build ${_BUILD_TARGETS} -c ${_bldtype}
