#!/bin/bash

set -e

rm -rf $HOME/.cache/bazel

_MOZC_BAZEL_CACHE=/tmp/mozc_cache

rm -rf $_MOZC_BAZEL_CACHE
for target in unix/fcitx5:fcitx5-mozc.so server:mozc_server gui/tool:mozc_tool; do
    # Only cquery accepts --config and it can also trigger the cache update
    bazel cquery --repository_cache="$_MOZC_BAZEL_CACHE" --config oss_linux $target
done

BASE=$PWD
pushd .
cd $_MOZC_BAZEL_CACHE
for f in `find -name 'id*' | sort` ; do
    echo "- type: file"
    echo -n "  url: "
    awk '{print $1}' $f
    echo "  dest: bazel-deps"
    sha=`dirname $f`
    sha=`basename $sha`
    echo "  sha256: $sha"
done > $BASE/mozc-deps.yaml
popd

rm -r $_MOZC_BAZEL_CACHE
