#!/bin/sh

_bldtype=Debug
PREFIX="${PREFIX:-/usr}"

for mofile in out_linux/Debug/gen/unix/fcitx/po/*.mo
do
    filename=`basename $mofile`
    lang=${filename/.mo/}
    install -D -m 644 "$mofile" "${PREFIX}/share/locale/$lang/LC_MESSAGES/fcitx-mozc.mo"
done

install -m 755 out_linux/Debug/fcitx-mozc.so ${PREFIX}/lib/fcitx/
install -m 644 unix/fcitx/fcitx-mozc.conf ${PREFIX}/share/fcitx/addon/
install -m 644 unix/fcitx/mozc.conf ${PREFIX}/share/fcitx/inputmethod/

install -d "${PREFIX}/share/fcitx/mozc/icon"
install -m 644 data/images/product_icon_32bpp-128.png ${PREFIX}/share/fcitx/mozc/icon/mozc.png
install -m 644 data/images/unix/ui-alpha_full.png ${PREFIX}/share/fcitx/mozc/icon/mozc-alpha_full.png
install -m 644 data/images/unix/ui-alpha_half.png ${PREFIX}/share/fcitx/mozc/icon/mozc-alpha_half.png
install -m 644 data/images/unix/ui-direct.png ${PREFIX}/share/fcitx/mozc/icon/mozc-direct.png
install -m 644 data/images/unix/ui-hiragana.png ${PREFIX}/share/fcitx/mozc/icon/mozc-hiragana.png
install -m 644 data/images/unix/ui-katakana_full.png ${PREFIX}/share/fcitx/mozc/icon/mozc-katakana_full.png
install -m 644 data/images/unix/ui-katakana_half.png ${PREFIX}/share/fcitx/mozc/icon/mozc-katakana_half.png
install -m 644 data/images/unix/ui-dictionary.png ${PREFIX}/share/fcitx/mozc/icon/mozc-dictionary.png
install -m 644 data/images/unix/ui-properties.png ${PREFIX}/share/fcitx/mozc/icon/mozc-properties.png
install -m 644 data/images/unix/ui-tool.png ${PREFIX}/share/fcitx/mozc/icon/mozc-tool.png
