#!/bin/sh
PREFIX="${PREFIX:-/usr}"

install -D -m 755 "bazel-bin/unix/fcitx5/fcitx5-mozc.so" "${PREFIX}/lib/fcitx5/fcitx5-mozc.so"

PREFIX="${PREFIX}" ../scripts/install_fcitx5_data
PREFIX="${PREFIX}" ../scripts/install_fcitx5_icons
