#!/bin/sh

set -e
MOZC_VERSION=`../scripts/get_mozc_version`

if [ "$?" != 0 -o -z MOZC_VERSION ]; then
    echo "Failed to get mozc version"
    exit 1
fi

xq -e --arg MOZC_VERSION "$MOZC_VERSION" '.component.releases.release[] | select(."@version" == $MOZC_VERSION)'  unix/fcitx5/org.fcitx.Fcitx5.Addon.Mozc.metainfo.xml.in && exit 1

DATE=`date +%Y-%m-%d`

xq -x --xml-dtd --arg MOZC_VERSION "$MOZC_VERSION" --arg DATE "$DATE" '.component.releases.release |= [{"@version": $MOZC_VERSION, "@date": $DATE}] + .' unix/fcitx5/org.fcitx.Fcitx5.Addon.Mozc.metainfo.xml.in > unix/fcitx5/org.fcitx.Fcitx5.Addon.Mozc.metainfo.xml.in.new

mv unix/fcitx5/org.fcitx.Fcitx5.Addon.Mozc.metainfo.xml.in{.new,}
